# Generated by Django 4.2 on 2024-09-09 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_payments_course_alter_payments_lesson_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
